# Generated by Django 6.0.5 on 2026-06-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepelement',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='stepelement',
            name='unique_step_element_order',
        ),
        migrations.RemoveField(
            model_name='stepelement',
            name='order',
        ),
    ]
