# Generated by Django 6.0.5 on 2026-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='stepelement',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_course_step_order',
        ),
        migrations.RemoveConstraint(
            model_name='stepelement',
            name='unique_step_element_order',
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Порядковый номер шага в курсе.'),
        ),
        migrations.AlterField(
            model_name='stepelement',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Порядковый номер контента в шаге.'),
        ),
    ]
