# Generated by Django 6.0.5 on 2026-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stepelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepelement',
            name='step_element_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('TEST', 'test')], max_length=10),
        ),
    ]
