# Generated by Django 6.0.5 on 2026-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stepelement_step_element_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepelement',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stepelement',
            name='order',
            field=models.PositiveIntegerField(default=678, help_text='Порядковый номер контента в шаге.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stepelement',
            name='step_element_type',
            field=models.CharField(choices=[('TEXT', 'текст'), ('TEST', 'тест')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='stepelement',
            constraint=models.UniqueConstraint(fields=('step', 'order'), name='unique_step_element_order'),
        ),
    ]
