# Generated by Django 6.0.5 on 2026-06-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_stepelement_options_stepelement_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepelement',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер контента в шаге.', null=True),
        ),
    ]
