# Generated by Django 6.0.5 on 2026-06-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stepelement_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stepelement',
            name='unique_step_element_order',
        ),
    ]
