# Generated by Django 6.0.5 on 2026-06-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_stepelement_unique_step_element_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_course_step_order',
        ),
    ]
