# Generated by Django 6.0.5 on 2026-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_step_unique_course_step_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_step_order'),
        ),
        migrations.AddConstraint(
            model_name='stepelement',
            constraint=models.UniqueConstraint(fields=('step', 'order'), name='unique_step_element_order'),
        ),
    ]
