# Generated by Django 6.0.5 on 2026-06-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_and_tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_lessons',
        ),
    ]
