# Generated by Django 6.0.5 on 2026-06-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_and_tests', '0002_rename_user_lesson_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
